### DISCUSSION TITLE
Contract metadata key registry

### DISCUSSION THREAD

**Discussion by ifropc** [stellar/stellar-protocol#1752] [Stellar Ecosystem Proposals]
### Background
Soroban contracts have WASM metadata, defined in [SEP-46](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0046.md). This SEP describes how metadata should be stored in the WASM. However, this SEP doesn't have any guidance on what metadata keys could be stored there.

### Motivation
With lack of centralized document with common keys it's hard to find which keys are used by other SEPs (unless you search other SEPs trying to find if they it turn support SEP-46),  and some common tools (such as Soroban SDK)  

### Proposal: standard metadata keys

We should add metadata key registry to SEP-46.
We should not make any attempts to strictly standardize it (i.e. it's okay for SEP to not list some fields using by some libraries or tools, but they are free to add the keys they are using to this list). With SEP-9 we discovered that it's sometimes hard to predict the usage of the SEP by the ecosystem, and very often people are using some fields that are not defined by the SEP. Given that, I strongly suggest we do not make any keys mandatory, at least not for the 'minimal' contract (or use case).
That being said, another SEPs (such as contract version SEP-49) should define mandatory (for this SEP) metadata keys, and I think it's a good idea to keep this "common" keys in once place.

We could add a table of 'commonly used keys':

| Key name     | Description                                             | Required by SEP         | Used by tool  |
| ------------ | ------------------------------------------------------- | ----------------------- | ------------- |
| `rsver`      | Version of rust used to compile WASM                    | N/A                     | Soroban SDK |
| `rssdkver`   | Soroban SDK dependency version used when compiling WASM | N/A                     | Soroban SDK |
| `name`       | The name of the contract                                | N/A                     | N/A           |
| `authors`    | The author(s) of the contract, often with an email      | N/A                     | N/A           |
| `homepage`   | The relevant domain to relate to this contract          | N/A                     | N/A           |
| `repository` | The source repository URL for the contract              | N/A                     | N/A           |
| `binver`     | The version of the WASM bytecode of the contract        | SEP-49 | N/A           |
| `sep`        | Indicates which SEPs contract claims to implement       | SEP-47 | N/A           |

### Proposal: Metadata keys in Cargo toml file

In addition, it would be nice to standardize following approach used in [Scaffold Stellar](https://github.com/AhaLabs/scaffold-stellar/pull/108) -- it allows users to put contract metadata in the contract's Cargo toml file and I think it improves user experience and other tools could benefit from supporting this feature.
Example of Cargo toml:
```toml
[package.metadata.stellar]
rsver = "ignored" # It's set by Soroban SDK and can not be overridden 
rssdkver = "ignored"
cargo_inherit = true # Specific to Scaffold but could be standardized. When set to 'true' will inherit , authors, homepage, repository and version from Cargo toml file 
name = "my-soroban-contract" # Even if we inherit a field, we could always override it 
home_domain = "example.com" # can be defined either as `homepage` or `home_domain`
repository = "https://github.com" # will be renamed to source_repo
my_custom_string = "foo"
my_custom_bool = true
my_custom_int = 1

[package.metadata.stellar.object]
simple_array = ["a", 123, false]
complex_array = ["a", { inner_array = ["b", "c"] }]
my_custom_object = { field1 = "val1", field2 = [ "single element array" ] }
``` 

And this is how it looks like when running `stellar contract info meta` on it:
```
> stellar contract info meta --wasm target/stellar/registry.wasm
ℹ️ Loading contract spec from file...
Contract meta:
 • rsver: 1.86.0 (Rust version)
 • rssdkver: 22.0.4#1d4afb3b981a4f4b2bbc19f0ce38af85c4ab316a (Soroban SDK version and it's commit hash)
 • authors: Example Authors <authors@example.com>
 • binver: 0.1.0
 • home_domain: example.com
 • my_custom_bool: true
 • my_custom_int: 1
 • my_custom_string: foo
 • name: soroban-registry
 • object.complex_array[0]: a
 • object.complex_array[1].inner_array: b,c
 • object.my_custom_object.field1: val1
 • object.my_custom_object.field2: single element array
 • object.simple_array: a,123,false
 • source_repo: https://github.com```
